version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi_app
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
